name: CI devops 2025

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # ğŸ§ª Ã‰tape 1 : Build, tests et analyse SonarCloud
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # 1ï¸âƒ£ RÃ©cupÃ©ration du code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour SonarCloud (analyse complÃ¨te de l'historique Git)

      # 2ï¸âƒ£ Installation de Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3ï¸âƒ£ Compilation et tests unitaires
      - name: Build and test with Maven
        run: mvn -B -f backend/pom.xml clean verify

      # 4ï¸âƒ£ Analyse du code avec SonarCloud
      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./backend
        run: >
          mvn -B verify sonar:sonar
          -Dsonar.projectKey=woodentouch_affdevops
          -Dsonar.organization=woodentouch
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  # ğŸ³ Ã‰tape 2 : Build et Push Docker (CD)
  build-and-push-docker-image:
    needs: test-backend  # Attend la rÃ©ussite des tests + analyse
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ğŸ” Connexion Ã  Docker Hub via secrets
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # ğŸ§± Build + push image backend
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # ğŸ—„ï¸ Build + push image database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./initdb
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # ğŸŒ Build + push image HTTP server
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
